name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.3
    - name: Run Lint
      run: make lint
    - name: Build
      run: make build
    - name: Run Tests
      run: make test-coverage
    # Upload coverage report if main is set
    - name: Upload Coverage Report
      if: matrix.os == 'ubuntu-latest' # only upload the report once
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: all.coverprofile # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
  win-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.3
    - name: Build
      run: make build
