---
name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/ .golangci.yml .goreleaser.yaml
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning
              line-length:
                level: warning
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - name: Run Lint
        run: make lint
      - name: Build
        run: make build
      - name: Run Tests
        run: make test-coverage
      - name: Upload Coverage Report
        if: matrix.os == 'ubuntu-latest'  # only upload the report once
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
          files: all.coverprofile
          flags: unittests
          fail_ci_if_error: true
  win-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - name: Build
        run: make build
