name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7
    - name: Run Lint
      run: make lint
    - name: Run Tests
      run: make test-coverage
    # Upload coverage report if main is set
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: all.coverprofile # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
