name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7
    - name: Run Lint
      run: make lint
    - name: Run Tests
      run: make test
