---
name: Release Docker images
on:
  push:
    branches:
      - 'develop'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.4
      - name: Build
        run: make build
      - name: Set commit sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push RC Nitric CLI to Dockerhub
        if: endsWith(github.ref, '/develop')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nitrictech/cli:rc-latest
            nitrictech/cli:rc-64
            nitrictech/cli:${{ steps.vars.outputs.sha_short }}
      - name: Push Main Nitric CLI to Dockerhub
        if: endsWith(github.ref, '/main')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nitrictech/cli:latest
            nitrictech/cli:x64
            nitrictech/cli:${{ steps.vars.outputs.sha_short }}
